config/routes.rb
Rails.application.routes.draw do

  root 'burgers#index'

    resources :burgers

end

app/models/burger.rb
class Burger < ActiveRecord::Base

include ActionView::Helpers::TextHelper
attr_accessor :sumbeef, :sumcheese, :sumonions
require 'set'

  def self.load

    if Burger.where(id:1).empty?

      default_burger = Burger.create(id:1, buns:"Extra Toasted")
    else

    end
  end

  def countcode
    wordstring = "#{self.beefcount}x#{self.cheesecount},#{self.frystyle},#{self.cheesestyle},#{self.spread},#{self.pickles},#{self.buns},#{self.cooklevel},#{self.onion1},#{self.onion2},#{self.onion3},#{self.onion4}"
    word = wordstring.split(",")
    self.result = word.to_set

    self.code = []

    #Count Onion Options. Push Onions @line-143. Need to count onions here in case Anial style takes GR
    onions = ["#{self.onion1}","#{self.onion2}","#{self.onion3}","#{self.onion4}"]
    raw = 0
    chop = 0
    whgr = 0
    gr = 0
    onions.each do |o|
      raw += 1 if o == "O"
      chop += 1 if o == "ChopO"
      whgr += 1 if o == "WHGR"
      gr += 1 if o == "GR"
    end

    #Dealing with MxC
    if self.result.include? "0x0"
      self.code << "Veggie"
    elsif self.result.include? "0x2"
      self.code << "Grill Chz"
    elsif self.result.include? "1x0"
      self.code << "HAMB"
    elsif self.result.include? "1x1"
      self.code << "CHB"
    elsif self.result.include? "2x0"
      self.code << "Dbl MEAT"
    elsif self.result.include? "2x2"
      self.code << "DblDbl"
    else
      self.code << "#{self.beefcount}x#{self.cheesecount}"
    end

    #Check Spread, Lettuce, Tomatoes. Push ">" if missing any.
    lt = ["#{self.lettuce}","#{self.tomatoes}"]
    if lt.include? ""
      self.code << ">"
    elsif self.spread == "" and self.ketchup == "" and self.mustard == ""
      self.code << ">"
    else
    end

    #Dealing with Animal Style
    animalstyle = Set["mfd","X S","P","GR"]
    if animalstyle.subset? self.result
      self.code << "Animal"
      gr -= 1
    end

    #Dealing with Core Condiments IF ">" presents
    if self.code.include? ">"
      self.code << "#{self.spread}" if self.spread == "S"
      self.code << "#{self.lettuce}" if self.lettuce == "L"
      self.code << "#{self.tomatoes}" if self.tomatoes == "T"
    end

    #Push onions
    if raw == 0 and chop == 0 and gr == 0 and whgr == 0
      self.code << "WO"
    end

    if raw == 1
      self.code << "raw"
    elsif raw > 1
      (raw-1).times {self.code << "X raw"}
    end

    if chop == 1
      self.code << "chop"
    elsif chop > 1
      (chop-1).times {self.code << "X chop"}
    end

    if gr == 1
      self.code << "GR"
    elsif gr > 1
      (gr-1).times {self.code << "X GR"}
    end

    if whgr == 1
      self.code << "WHGR"
    elsif whgr > 1
      (whgr-1).times {self.code << "X WHGR"}
    end

    #Dealing with Spread
    if self.spread == "X S"
      self.code << self.spread unless self.code.include? "Animal"
    else
    end

    #Dealing with Lettuce
    if self.lettuce == "X L"
      self.code << self.lettuce unless self.code.include? "X L"
    else
    end

    #Dealing with Tomatoes
    if self.tomatoes == "X T"
      self.code << self.tomatoes unless self.code.include? "X T"
    else
    end

    #Dealing with pickles
    self.code << "#{self.pickles}" if self.pickles != ""

    #Dealing with other requests
    self.code << "#{self.cheesestyle}" if self.cheesestyle == "Cold_cheese"
    self.code << "#{self.chopchillies}" if self.chopchillies != ""
    self.code << "#{self.extrasalt}" if self.extrasalt != ""
    self.code << "#{self.mustard}" if self.mustard != ""
    self.code << "#{self.ketchup}" if self.ketchup != ""
    mustard_inst = (self.mustard != "" and self.spread == '')
    ketchup_inst = (self.ketchup != "" and self.spread == '')
    if self.code.include? ">"
    elsif mustard_inst or ketchup_inst
      self.code << "Inst"
    end

    # Dealing with Fry Style
    self.code << "#{self.frystyle}" if self.frystyle != " "

    #Add "only" here. >> This is the end of condiments code <<
    self.code << "only" if self.code.include? ">"

    #Bun Request
    self.code << "#{self.cooklevel}" if self.cooklevel != " "

    #Dealing with buns request. Flying Dutchman needs special handling
    if self.buns != "" and self.buns != "FLYING DUTCHMAN"
      self.code << "#{self.buns}"

      #Dealing with Flying Dutchman when code includes irregular burgers: 2x1, 2x3, etc.
    elsif self.buns == "FLYING DUTCHMAN" and self.code.include? "#{self.beefcount}x#{self.cheesecount}"
      self.code.unshift("#{self.buns}")

      #Dealing with Flying Dutchman when code includes regular burgers: HAMB, CHB, etc.
    else
      self.code.unshift("#{self.beefcount}x#{self.cheesecount}")
      self.code.unshift("#{self.buns}")
      #Get rid of "HAMB", "CHB", etc.
      list = ["HAMB","CHB","Dbl MEAT","DblDbl"]
      list.each do |l|
        if self.code.include? l
          self.code.delete(l)
        end
      end
    end

    #Check if XE condition exists
    extra_everything = Set["X T","X L","X raw","X S","P","chillies"]
    check_code = self.code.to_set
    if extra_everything.subset? check_code
      self.code.insert(1,"XE")
      self.code.delete('X T')
      self.code.delete('X L')
      self.code.delete('X raw')
      self.code.delete('X S')
      self.code.delete('P')
      self.code.delete('chillies')
    end

    #Dealing with "Cut in Half" request
    self.code << "#{self.cutinhalf}" if self.cutinhalf != ""

    #Clean up "WO" if "only" exists
    self.code.delete("WO") if self.code.include? "only"

    #Clean up Animal Style Ingredients if "Animal" exists
    if self.code.include? "Animal"
      self.code.delete('mfd')
      self.code.delete('X S')
      self.code.delete('P')
    end


    #self.code = self.code.uniq
    self.code = self.code*" "

  end

#Burger.load
end

private

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
before_filter :checkAnimal

  def index
    @burgers = Burger.all
  end

  def new
    @burger = Burger.new(burger_params)

  end

  def edit
    @burger = Burger.find(params[:id])
  end

  def create
    @burger = Burger.new(burger_params)

    if @burger.save
      redirect_to @burger
    else
      render 'new'
    end
  end

  def show
    @burger = Burger.find(params[:id])
  end

  def destroy
    @burger = Burger.find(params[:id])
    @burger.destroy
    redirect_to burgers_path
  end

  def update
    @burger = Burger.find(params[:id])
    if @burger.update(burger_params)
      redirect_to @burger
    else
      render 'edit'
    end
  end

  def checkAnimal
    @burger = Burger.new
    animal = {onion1:"GR",frystyle:"mfd",spread:"X S",pickles:"P"}

    if params[:animalstyle] =="1"
      burger_params.merge(pickles:"P")
    end
  end
private
  def burger_params
    params.require(:burger).permit(:buns, :patties,
      :cheese, :onions, :tomatoes, :lettuce, :spreads,
      :others, :cutinhalf, :cooklevel, :heavymustardbeef,
      :normalmustardbeef, :normalbeef, :nosaltbeef, :meltcheese, :coldcheese,
      :rawwholeonions, :rawchoponions, :grillwholeonions, :grillchoponions,
      :sumbeef, :sumcheese, :sumonions, :spread, :mustard, :ketchup, :extrasalt,
      :pickles, :chopchillies, :condiments, :specialrequests, :animalstyle,
      :result, :code, :frystyle, :beefcount, :cheesestyle, :cheesecount, :onionstyle,
      :onioncount, :onion1, :onion2, :onion3, :onion4)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/views/burgers/_form.html.erb
<%= form_for @burger do |f| %>

	<% if @burger.errors.any? %>

	<div id="error_explanation">
		<h2><font color="DAA520">* <%= pluralize(@burger.errors.count, "Error") %> Prohibited This Burger from Being Saved. Detail Below in Red *</font></h2>
	<ul>

	<% @burger.errors.full_messages.each do |msg| %>
		<li ><font color="#FF4500"><%= msg %></font></li>
	<% end %>

	</ul>
	</div>

	<% end %>

	<p>
		<%= f.check_box :cutinhalf, {}, "1/2", "" %>
		<%= f.label 'Cut in half?' %>
		<%= f.check_box :animalstyle, {}, "Animal", "" %>
		<%= f.label 'Animal Style' %>
	</p>

	<p>
		<h4><%= f.label 'Choose buns here:' %></h4>
		<%= f.radio_button(:buns,'X toast') %>
		<%= f.label(:buns, "Extra Toasted") %>

		<%= f.radio_button(:buns, " ") %>
		<%= f.label(:buns, "Original Toasted") %>

		<%= f.radio_button(:buns, 'no_toast') %>
		<%= f.label(:buns, "Untoasted") %>

		<%= f.radio_button(:buns, 'pro') %>
		<%= f.label(:buns, "Lettuce") %>

		<%= f.radio_button(:buns, 'FLYING DUTCHMAN') %>
		<%= f.label(:buns, "No Bun") %>
	</p>

	<p>
		<h4><%= f.label 'Customize Beef Patties here:' %></h4>
		<h4><%= f.label 'Cook level:' %></h4>
		<%= f.radio_button(:cooklevel,'md_rare') %>
		<%= f.label(:cooklevel, "Medium Rare") %>
		<%= f.radio_button(:cooklevel, ' ') %>
		<%= f.label(:cooklevel, "Medium Well") %>
		<%= f.radio_button(:cooklevel, 'well') %>
		<%= f.label(:cooklevel, "Well Done") %>
	</p>

	<p>
	<h4><%= f.label 'Frying Style:' %></h4>
		<%= f.radio_button(:frystyle, " ") %>
		<%= f.label(:frystyle, 'Normal Fry') %>
		<%= f.radio_button(:frystyle, 'no_salt') %>
		<%= f.label(:frystyle, 'No Salt') %>
		<%= f.radio_button(:frystyle, 'mfd') %>
		<%= f.label(:frystyle, 'Mustard Fry') %>
		<input type="button" value="uncheck 'em" onclick="for(i=o;i<test.length;i++)test[i].checked=false>"
	</p>

	<p>
		<h4><%= f.label 'How Many Beef Patties? (total up to 4 patties per burger):' %></h4>
		<%= f.label 'Beef' %> <%= f.select :beefcount, options_for_select([["-Select-", "0"], "1", "2", "3", "4"], :selected => @burger.beefcount) %><br>
	</p>

	<p>
	<h4><%= f.label 'Cheese Style:' %></h4>
		<%= f.radio_button(:cheesestyle,'meltcheese') %>
		<%= f.label(:cheesestyle, 'Melted Cheese') %>
		<%= f.radio_button(:cheesestyle, 'Cold_cheese') %>
		<%= f.label(:cheesestyle, 'Cold Cheese') %>
	</p>
		

	<p>
		<h4><%= f.label 'Select Cheese Amount (total up to 4 slices per burger):' %></h4>
		<%= f.label 'Cheese' %> <%= f.select :cheesecount, options_for_select([["-Select-", "0"], "1", "2", "3", "4"], :selected => @burger.cheesecount ) %><br>
	</p>

	<p>
		<h4><%= f.label 'Customize onions here (total up to 4 portions per burger):' %></h4>
		<%= f.label 'Onion 1' %> <%= f.select :onion1, options_for_select([["-Select-", ""], ["Fresh Whole Onion","O"], ["Fresh Chopped Onion","ChopO"], ["Grilled Whole Onion","WHGR"], ["Grilled Chopped Onion","GR"]], :selected => @burger.onion1 ) %><br>
		<%= f.label 'Onion 2' %> <%= f.select :onion2, options_for_select([["-Select-", ""], ["Fresh Whole Onion","O"], ["Fresh Chopped Onion","ChopO"], ["Grilled Whole Onion","WHGR"], ["Grilled Chopped Onion","GR"]], :selected => @burger.onion2 ) %><br>
		<%= f.label 'Onion 3' %> <%= f.select :onion3, options_for_select([["-Select-", ""], ["Fresh Whole Onion","O"], ["Fresh Chopped Onion","ChopO"], ["Grilled Whole Onion","WHGR"], ["Grilled Chopped Onion","GR"]], :selected => @burger.onion3 ) %><br>
		<%= f.label 'Onion 4' %> <%= f.select :onion4, options_for_select([["-Select-", ""], ["Fresh Whole Onion","O"], ["Fresh Chopped Onion","ChopO"], ["Grilled Whole Onion","WHGR"], ["Grilled Chopped Onion","GR"]], :selected => @burger.onion4 ) %>
	</p>


	<p>
	<h4><%= f.label 'Add Lettuce Here:' %></h4>
		<%= f.label 'Fresh Lettuce' %> <%= f.select :lettuce, options_for_select([["-Select-", ""],["Normal","L"], ["Extra","X L"]], :selected => @burger.lettuce ) %>
	</p>

	<p>
	<h4><%= f.label 'Tomatoes, anyone?' %></h4>
		<%= f.label 'Fresh Tomatoes' %> <%= f.select :tomatoes, options_for_select([["-Select-", ""], ["Normal","T"], ["Extra","X T"]], :selected => @burger.tomatoes ) %>
	</p>

	<p>
		<h4><%= f.label 'Choose spread here:' %></h4>
		<%= f.radio_button(:spread,'X S') %>
		<%= f.label(:spread, "Extra Spread") %>
		<%= f.radio_button(:spread, 'S') %>
		<%= f.label(:spread, "Normal Spread") %>
		<%= f.radio_button(:spread, '') %>
		<%= f.label(:spread, "No Spread") %>
	</p>

	<p>
		<h4><%= f.label 'Choose condiments here:' %></h4>
		<%= f.check_box :mustard, {}, "M", "" %><%= f.label 'Mustard' %>
		<%= f.check_box :ketchup, {}, "K", "" %><%= f.label 'Ketchup' %>
		<%= f.check_box :extrasalt, {}, "X Salt", "" %><%= f.label 'Extra Salt' %>
		<%= f.check_box :pickles, {}, "P", "" %><%= f.label 'Pickles' %>
		<%= f.check_box :chopchillies, {}, "chillies", "" %><%= f.label 'Chopped Chillies' %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/burgers/edit.html.erb
<h1> Edit Your Yummy Burger Here :) </h1>

<%= render 'form' %>

<%= link_to 'Back', burgers_path %>

app/views/burgers/index.html.erb
<h1>Burger List</h1>

<%= check_box_tag 'animalstyle' %>Animal Style?


<h3><%= link_to "Create Custom Burger", new_burger_path(burger:{buns:""}) %></h3>

<h3><%= link_to "Create Veggie Burger", new_burger_path(:burger=>{buns:" ",lettuce:"L",tomatoes:"T",spread:"S"}, :buns => ("no_toast" if :animalstyle == "1")) %></h3>

<h3><%= link_to "Create Hamburger", new_burger_path(:burger=>{buns:" ", cooklevel:" ",frystyle:" ",beefcount:"1",lettuce:"L",tomatoes:"T",spread:"S"}, :buns => ("no_toast" if :animalstyle == "1")) %></h3>

<h3><%= link_to "Create Cheeseburger", new_burger_path(:burger=>{buns:" ", cooklevel:" ",frystyle:" ",beefcount:"1",cheesestyle:"meltcheese",cheesecount:"1",lettuce:"L",tomatoes:"T",spread:"S"}, :buns => ("no_toast" if :animalstyle == "1")) %></h3>

<h3><%= link_to "Create Double Double Burger", new_burger_path(:burger=>{buns:" ", cooklevel:" ",frystyle:" ",beefcount:"2",cheesestyle:"meltcheese",cheesecount:"2",lettuce:"L",tomatoes:"T",spread:"S"}, :buns => ("no_toast" if :animalstyle == "1")) %></h3>

<table border="1">
	<tr>
		<th>ID</th>
		<th>Burger Name</th>
		<th>Description</th>
		<th colspan="3">Actions</th>
	</tr>

	<% @burgers.each do |burger| %>
	<% burger.countcode %>
		<tr>
			<td><%= link_to burger.id, burger %></td>
			<td><%= link_to burger.id, burger %></td>
			<td><%= burger.code %></td>
			<td><%= link_to 'View Burger', burger %></td>
			<td><%= link_to 'Edit', edit_burger_path(burger) %></td>
			<td><%= link_to 'Delete Burger', burger_path(burger), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		</tr>
	<% end %>
	
</table>

app/views/burgers/new.html.erb
<h1> Let's Create Your In-N-Out Burger! </h1>
<h2> First, Pick From Secret Menu </h2>

<%= render 'form' %>

<%= link_to 'Back', burgers_path %>

app/views/burgers/pickmenu.html.erb
<h1>In-N-Out Secret Menu</h1>

<%= render 'menu' %>

<%= link_to 'Back', burgers_path %>

app/views/burgers/show.html.erb
<p>
	<strong>Burger ID:</strong>
	<%= @burger.id %>
</p>

<$ @burger.countspecialrequests %>
<p>
	<strong>Special Request:</strong>
	<%= @burger.specialrequests %>
</p>

<p>
	<strong>Buns:</strong>
	<%= @burger.buns %>
</p>

<p>
	<strong>Cook Request:</strong>
	<%= @burger.cooklevel %>
</p>

<$ @burger.countpatties %>
<p>
	<strong>Patties:</strong> 
	<%= @burger.patties %>
</p>

<$ @burger.countcheese %>
<p>
	<strong>Cheese:</strong> 
	<%= @burger.cheese %>
</p>

<$ @burger.countonions %>
<p>
	<strong>Onions:</strong>
	<%= @burger.onions %>
</p>

<p>
	<strong>Onion Options:</strong>
	<%= @burger.onion1 %>
	<%= @burger.onion2 %>
	<%= @burger.onion3 %>
	<%= @burger.onion4 %>
</p>

<$ @burger.counttomatoes %>
<p>
	<strong>Tomatoes:</strong>
	<%= @burger.tomatoes %>
</p>

<$ @burger.countlettuce %>
<p>
	<strong>Lettuce:</strong>
	<%= @burger.lettuce %>
</p>

<p>
	<strong>Spread:</strong>
	<%= @burger.spread %>
</p>

<$ @burger.countcondiments %>
<p>
	<strong>Condiments:</strong>
	<%= @burger.condiments %>
</p>

<$ @burger.countresult %>
<p>
	<strong>Result:</strong>
	<%= @burger.result %>
</p>

<% @burger.countcode %>
<p>
	<strong>In-N-Out Code for your order:</strong>
	<%= @burger.code %>
</p>


<%= link_to 'Back', burgers_path %>
<%= link_to 'Edit', edit_burger_path(@burger) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Innoutmenu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>